version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: booking-app-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-booking_app}
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/booking_app --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      
  # Thêm mongo-express để quản lý MongoDB qua giao diện web
  mongo-express:
    image: mongo-express
    container_name: booking-app-mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
